In [8]:
using Statistics
function Combine_Score(scores)
    combinationScores = []
    n = length(scores)
    for i in 1:n # get combined score for the scenario where the motif appear in i sequences
        A = ones(i, n) # This is the dp matrix. the A_i_n element in the matrix will give us the final answer
        for x in 1:i
            for y in 1:n
                if(x > y)
                    A[x, y] = 0
                elseif(x == 1)
                    if(y == 1)
                        A[x, y] = (x * scores[y] * 1 + (y-x) * 0) / y
                    else
                        A[x, y] = (x * scores[y] * 1 + (y-x) * A[x,(y-1)]) / y
                    end
                else
                    A[x, y] = (x * scores[y] * A[(x-1),(y-1)] + (y-x) * A[x,(y-1)]) / y
                end
            end
        end
        push!(combinationScores, A[i, n])
    end
    return mean(combinationScores)
end

a = [0.3, 0.4, 0.5, 0.3, 0.4, 0.5]
Combine_Score(a)

1×6 Array{Float64,2}:
 0.3  0.35  0.4  0.375  0.38  0.4

2×6 Array{Float64,2}:
 0.3  0.35  0.4       0.375     0.38   0.4     
 0.0  0.12  0.156667  0.138333  0.143  0.158667

3×6 Array{Float64,2}:
 0.3  0.35  0.4       0.375     0.38    0.4     
 0.0  0.12  0.156667  0.138333  0.143   0.158667
 0.0  0.0   0.06      0.05025   0.0533  0.0624  

4×6 Array{Float64,2}:
 0.3  0.35  0.4       0.375     0.38     0.4      
 0.0  0.12  0.156667  0.138333  0.143    0.158667 
 0.0  0.0   0.06      0.05025   0.0533   0.0624   
 0.0  0.0   0.0       0.018     0.01968  0.0243267

5×6 Array{Float64,2}:
 0.3  0.35  0.4       0.375     0.38     0.4      
 0.0  0.12  0.156667  0.138333  0.143    0.158667 
 0.0  0.0   0.06      0.05025   0.0533   0.0624   
 0.0  0.0   0.0       0.018     0.01968  0.0243267
 0.0  0.0   0.0       0.0       0.0072   0.0094   

6×6 Array{Float64,2}:
 0.3  0.35  0.4       0.375     0.38     0.4      
 0.0  0.12  0.156667  0.138333  0.143    0.158667 
 0.0  0.0   0.06      0.05025   0.0533   0.0624   
 0.0  0.0   0.0       0.018     0.01968  0.0243267
 0.0  0.0   0.0       0.0       0.0072   0.0094   
 0.0  0.0   0.0       0.0       0.0      0.0036   

0.10973222222222222

In [4]:
a = [[1 2 3];[4 5 6]]
display(a)
a[2,1]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

4