In [6]:
function Get_Single_Strand_Motifs(fileName)
    ssPFMs = []
    currentPFM = []
    motifTitles = []
    open(fileName) do file
        title = ""
        while !eof(file)
            line = readline(file)
            if(line[1:1] == ">")
                if(title == "")
                    title = line
                end
                #record what has been read so far
                if(length(currentPFM) > 0) 
                    push!(motifTitles, title)
                    currentPFM = Normalize(currentPFM, 0.1)
                    push!(ssPFMs, currentPFM)
                    currentPFM = []
                end
                #update the current title after the old one is recorded
                title = line 
            elseif(line[1:1] == "#")
                #do nothing since this line is comment
            else
                frequencies = split(line, r"\s")
                if(length(frequencies) == 4) #each line should only have 4 numbers seperated by spaces 
                    row = []
                    for frequency in frequencies
                        d = parse(Int, frequency)
                        push!(row, d)
                    end
                    push!(currentPFM, row)
                else
                    println(line)
                    println("this line has $(length(counts)) elements")
                end
                if(eof(file))
                    currentPFM = Normalize(currentPFM, 0.1)
                    push!(ssPFMs, currentPFM)
                end
            end                
        end
    end
    return ssPFMs
end

function Normalize(matrix, psuedoCount)
    nrow = length(matrix)
    ncol = length(matrix[1])
    row = ones(ncol) * psuedoCount
    psuedoMatrix = []
    for i in 1:nrow
        push!(psuedoMatrix, row)
    end
    newMatrix = matrix + psuedoMatrix
    return Normalize(newMatrix)
end

function Normalize(matrix)
    normalizedMatrix = []
    for row in matrix
        row = row/sum(row)
        push!(normalizedMatrix, row)
    end
    return normalizedMatrix
end

function Get_Reverse_Complement(motif)
    reverseComplement = []
    for row in motif
        newRow = reverse(row)
        push!(reverseComplement, newRow)
    end
    reverse!(reverseComplement)
    return reverseComplement
end


function Get_Double_Strand_Motifs(singleStrandMotifs, realDoubleStrand)
    doubleStrandMotifs = []
    for motif in singleStrandMotifs
        strands = []
        temp_motif = deepcopy(motif)
        # add a column of zeros
        for row in motif
            push!(row, 0)
        end
        push!(strands, motif)
        if(realDoubleStrand)
            reverseComplement = Get_Reverse_Complement(temp_motif)
            for row in reverseComplement
                push!(row, 0)
            end
            push!(strands, reverseComplement)
        end

        push!(doubleStrandMotifs, strands)
        
    end
    return doubleStrandMotifs
end


#singleStrandMotifs = Get_Single_Strand_Motifs("test.txt")
#display(singleStrandMotifs)
#doubleStrandMotifs = Get_Double_Strand_Motifs(singleStrandMotifs, true)
#display(doubleStrandMotifs)

2-element Array{Any,1}:
 [8, 7, 6, 5]
 [4, 3, 2, 1]

2-element Array{Any,1}:
 Any[[0.0010266940451745382, 0.9661190965092404, 0.011293634496919922, 0.021560574948665305], [0.031827515400410684, 0.7710472279260782, 0.0010266940451745382, 0.1960985626283368], [0.8121149897330597, 0.042094455852156064, 0.031827515400410684, 0.11396303901437374], [0.4117043121149897, 0.03182751540041068, 0.04209445585215605, 0.5143737166324435], [0.6786447638603698, 0.011293634496919922, 0.011293634496919922, 0.2987679671457906], [0.49383983572895274, 0.021560574948665298, 0.001026694045174538, 0.48357289527720737], [0.6683778234086243, 0.05236139630390144, 0.05236139630390144, 0.22689938398357296], [0.11396303901437373, 0.0215605749486653, 0.031827515400410684, 0.8326488706365504], [0.6683778234086243, 0.031827515400410684, 0.28850102669404526, 0.011293634496919922], [0.0010266940451745382, 0.031827515400410684, 0.904517453798768, 0.06262833675564682]]
 Any[[0.0005393743257820928, 0.0005393743257820928, 0.9983818770226538, 0.0005393743257820928], [0.0005393

2-element Array{Any,1}:
 Any[Any[[0.0010266940451745382, 0.9661190965092404, 0.011293634496919922, 0.021560574948665305, 0.0], [0.031827515400410684, 0.7710472279260782, 0.0010266940451745382, 0.1960985626283368, 0.0], [0.8121149897330597, 0.042094455852156064, 0.031827515400410684, 0.11396303901437374, 0.0], [0.4117043121149897, 0.03182751540041068, 0.04209445585215605, 0.5143737166324435, 0.0], [0.6786447638603698, 0.011293634496919922, 0.011293634496919922, 0.2987679671457906, 0.0], [0.49383983572895274, 0.021560574948665298, 0.001026694045174538, 0.48357289527720737, 0.0], [0.6683778234086243, 0.05236139630390144, 0.05236139630390144, 0.22689938398357296, 0.0], [0.11396303901437373, 0.0215605749486653, 0.031827515400410684, 0.8326488706365504, 0.0], [0.6683778234086243, 0.031827515400410684, 0.28850102669404526, 0.011293634496919922, 0.0], [0.0010266940451745382, 0.031827515400410684, 0.904517453798768, 0.06262833675564682, 0.0]], Any[[0.06262833675564682, 0.904517453798768, 0.0318

In [ ]:
Get_Motifs("jaspar2009core.fa")